// Generated by uniffi-bindgen-react-native
import installer from './NativeController';
import dojoInstaller from './NativeDojo';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
console.log('🔍 Checking native modules...');
console.log('Controller installer:', installer);
console.log('Dojo installer:', dojoInstaller);

// Check if modules are available
const controllerAvailable = installer && typeof installer.installRustCrate === 'function';
const dojoAvailable = dojoInstaller && typeof dojoInstaller.installRustCrate === 'function';

console.log('Controller available:', controllerAvailable);
console.log('Dojo available:', dojoAvailable);

if (!controllerAvailable) {
  throw new Error('❌ CRITICAL: Controller native module not found! Make sure the iOS build completed successfully.');
}

if (!dojoAvailable) {
  throw new Error('❌ CRITICAL: Dojo native module not found! Make sure the iOS build completed successfully.');
}

try {
  console.log('⚙️ Installing Controller crate...');
  const controllerResult = installer.installRustCrate();
  console.log('✅ Controller crate installed, result:', controllerResult);
  
  // Check if global.NativeController is now available
  const hasNativeController = typeof (globalThis as any).NativeController !== 'undefined';
  console.log('globalThis.NativeController available:', hasNativeController);
  if (hasNativeController) {
    console.log('NativeController keys:', Object.keys((globalThis as any).NativeController || {}).slice(0, 5));
  }
} catch (e) {
  console.error('❌ Error installing Controller:', e);
  throw e;
}

try {
  console.log('⚙️ Installing Dojo crate...');
  const dojoResult = dojoInstaller.installRustCrate();
  console.log('✅ Dojo crate installed, result:', dojoResult);
  
  // Check if global.NativeDojo is now available
  const hasNativeDojo = typeof (globalThis as any).NativeDojo !== 'undefined';
  console.log('globalThis.NativeDojo available:', hasNativeDojo);
  if (hasNativeDojo) {
    console.log('NativeDojo keys:', Object.keys((globalThis as any).NativeDojo || {}).slice(0, 5));
  }
} catch (e) {
  console.error('❌ Error installing Dojo:', e);
  throw e;
}

console.log('✅ All Rust crates installed successfully!');

// NOW it's safe to import the generated bindings
// Export the generated bindings to the app.
export * from './generated/controller';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as controller from './generated/controller';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  controller.default.initialize();
  initialized = true;
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

// Export the crates as individually namespaced objects.
export default {
  controller,
};

