// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.10.0+v0.29.4
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
namespace uniffi.controller_uniffi;
using FfiConverterTypeFieldElement = FfiConverterString;
using FieldElement = String;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_controller_uniffi_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_controller_uniffi_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
internal class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

internal class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

internal class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

internal class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

internal class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

internal class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

internal class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

internal class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
static class _UniFFILib {
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFuture
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructPointer
    {
        public IntPtr @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompletePointer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructPointer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructVoid @result
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr uniffi_controller_uniffi_fn_clone_controllerinfo(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_controller_uniffi_fn_free_controllerinfo(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr uniffi_controller_uniffi_fn_constructor_controllerinfo_new(RustBuffer @appId,RustBuffer @username,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_controller_uniffi_fn_method_controllerinfo_format_info(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_controller_uniffi_fn_method_controllerinfo_get_app_id(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_controller_uniffi_fn_method_controllerinfo_get_username(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_controller_uniffi_fn_func_format_call(RustBuffer @call,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte uniffi_controller_uniffi_fn_func_validate_felt(RustBuffer @felt,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_controller_uniffi_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_controller_uniffi_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_controller_uniffi_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_u8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_u8(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_u8(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte ffi_controller_uniffi_rust_future_complete_u8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_i8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_i8(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_i8(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte ffi_controller_uniffi_rust_future_complete_i8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_u16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_u16(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_u16(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort ffi_controller_uniffi_rust_future_complete_u16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_i16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_i16(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_i16(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern short ffi_controller_uniffi_rust_future_complete_i16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_u32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_u32(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_u32(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_controller_uniffi_rust_future_complete_u32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_i32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_i32(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_i32(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern int ffi_controller_uniffi_rust_future_complete_i32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_u64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_u64(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_u64(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong ffi_controller_uniffi_rust_future_complete_u64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_i64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_i64(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_i64(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern long ffi_controller_uniffi_rust_future_complete_i64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_f32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_f32(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_f32(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern float ffi_controller_uniffi_rust_future_complete_f32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_f64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_f64(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_f64(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern double ffi_controller_uniffi_rust_future_complete_f64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_pointer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_pointer(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_pointer(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ffi_controller_uniffi_rust_future_complete_pointer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_rust_buffer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_rust_buffer(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_rust_buffer(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_controller_uniffi_rust_future_complete_rust_buffer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_poll_void(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_cancel_void(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_free_void(IntPtr @handle
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_controller_uniffi_rust_future_complete_void(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_controller_uniffi_checksum_func_format_call(
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_controller_uniffi_checksum_func_validate_felt(
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_controller_uniffi_checksum_method_controllerinfo_format_info(
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_controller_uniffi_checksum_method_controllerinfo_get_app_id(
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_controller_uniffi_checksum_method_controllerinfo_get_username(
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_controller_uniffi_checksum_constructor_controllerinfo_new(
    );

    [DllImport("controller_uniffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_controller_uniffi_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_controller_uniffi_uniffi_contract_version();
        if (29 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"uniffi.controller_uniffi: uniffi bindings expected version `29`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_controller_uniffi_checksum_func_format_call();
            if (checksum != 53782) {
                throw new UniffiContractChecksumException($"uniffi.controller_uniffi: uniffi bindings expected function `uniffi_controller_uniffi_checksum_func_format_call` checksum `53782`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_controller_uniffi_checksum_func_validate_felt();
            if (checksum != 55035) {
                throw new UniffiContractChecksumException($"uniffi.controller_uniffi: uniffi bindings expected function `uniffi_controller_uniffi_checksum_func_validate_felt` checksum `55035`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_controller_uniffi_checksum_method_controllerinfo_format_info();
            if (checksum != 35530) {
                throw new UniffiContractChecksumException($"uniffi.controller_uniffi: uniffi bindings expected function `uniffi_controller_uniffi_checksum_method_controllerinfo_format_info` checksum `35530`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_controller_uniffi_checksum_method_controllerinfo_get_app_id();
            if (checksum != 58700) {
                throw new UniffiContractChecksumException($"uniffi.controller_uniffi: uniffi bindings expected function `uniffi_controller_uniffi_checksum_method_controllerinfo_get_app_id` checksum `58700`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_controller_uniffi_checksum_method_controllerinfo_get_username();
            if (checksum != 22156) {
                throw new UniffiContractChecksumException($"uniffi.controller_uniffi: uniffi bindings expected function `uniffi_controller_uniffi_checksum_method_controllerinfo_get_username` checksum `22156`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_controller_uniffi_checksum_constructor_controllerinfo_new();
            if (checksum != 24422) {
                throw new UniffiContractChecksumException($"uniffi.controller_uniffi: uniffi bindings expected function `uniffi_controller_uniffi_checksum_constructor_controllerinfo_new` checksum `24422`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value) {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}



internal interface IControllerInfo {
    string FormatInfo();
    string GetAppId();
    string GetUsername();
}
internal class ControllerInfo : IControllerInfo, IDisposable {
    protected IntPtr pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public ControllerInfo(IntPtr pointer) {
        this.pointer = pointer;
    }

    ~ControllerInfo() {
        Destroy();
    }
    public ControllerInfo(string @appId, string @username) :
        this(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_controller_uniffi_fn_constructor_controllerinfo_new(FfiConverterString.INSTANCE.Lower(@appId), FfiConverterString.INSTANCE.Lower(@username), ref _status)
)) {}

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_controller_uniffi_fn_free_controllerinfo(this.pointer, ref status);
        });
    }

    protected IntPtr CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_controller_uniffi_fn_clone_controllerinfo(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<IntPtr> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<IntPtr, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    public string FormatInfo() {
        return CallWithPointer(thisPtr => FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_controller_uniffi_fn_method_controllerinfo_format_info(thisPtr,  ref _status)
)));
    }
    
    
    public string GetAppId() {
        return CallWithPointer(thisPtr => FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_controller_uniffi_fn_method_controllerinfo_get_app_id(thisPtr,  ref _status)
)));
    }
    
    
    public string GetUsername() {
        return CallWithPointer(thisPtr => FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_controller_uniffi_fn_method_controllerinfo_get_username(thisPtr,  ref _status)
)));
    }
    
    

    
}
class FfiConverterTypeControllerInfo: FfiConverter<ControllerInfo, IntPtr> {
    public static FfiConverterTypeControllerInfo INSTANCE = new FfiConverterTypeControllerInfo();


    public override IntPtr Lower(ControllerInfo value) {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override ControllerInfo Lift(IntPtr value) {
        return new ControllerInfo(value);
    }

    public override ControllerInfo Read(BigEndianStream stream) {
        return Lift(new IntPtr(stream.ReadLong()));
    }

    public override int AllocationSize(ControllerInfo value) {
        return 8;
    }

    public override void Write(ControllerInfo value, BigEndianStream stream) {
        stream.WriteLong(Lower(value).ToInt64());
    }
}



internal record Call (
    string @contractAddress, 
    string @entrypoint, 
    string[] @calldata
) {
}

class FfiConverterTypeCall: FfiConverterRustBuffer<Call> {
    public static FfiConverterTypeCall INSTANCE = new FfiConverterTypeCall();

    public override Call Read(BigEndianStream stream) {
        return new Call(
            @contractAddress: FfiConverterString.INSTANCE.Read(stream),
            @entrypoint: FfiConverterString.INSTANCE.Read(stream),
            @calldata: FfiConverterSequenceString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(Call value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@contractAddress)
            + FfiConverterString.INSTANCE.AllocationSize(value.@entrypoint)
            + FfiConverterSequenceString.INSTANCE.AllocationSize(value.@calldata);
    }

    public override void Write(Call value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@contractAddress, stream);
            FfiConverterString.INSTANCE.Write(value.@entrypoint, stream);
            FfiConverterSequenceString.INSTANCE.Write(value.@calldata, stream);
    }
}





internal class ControllerException: UniffiException {
    ControllerException() : base() {}
    ControllerException(String @Message) : base(@Message) {}

    // Each variant is a nested class
    
    
    public class InitializationException : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public InitializationException(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    
    
    public class SignupException : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public SignupException(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    
    
    public class ExecutionException : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public ExecutionException(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    
    
    public class NetworkException : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public NetworkException(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    
    
    public class StorageException : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public StorageException(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    
    
    public class InvalidInput : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public InvalidInput(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    
    
    public class DisconnectException : ControllerException {
        // Members
        public string @v1;

        // Constructor
        public DisconnectException(
                string @v1) : base(
                "@v1" + "=" + @v1) {

            this.@v1 = @v1;
        }
    }
    

    
}

class FfiConverterTypeControllerError : FfiConverterRustBuffer<ControllerException>, CallStatusErrorHandler<ControllerException> {
    public static FfiConverterTypeControllerError INSTANCE = new FfiConverterTypeControllerError();

    public override ControllerException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new ControllerException.InitializationException(
                    FfiConverterString.INSTANCE.Read(stream));
            case 2:
                return new ControllerException.SignupException(
                    FfiConverterString.INSTANCE.Read(stream));
            case 3:
                return new ControllerException.ExecutionException(
                    FfiConverterString.INSTANCE.Read(stream));
            case 4:
                return new ControllerException.NetworkException(
                    FfiConverterString.INSTANCE.Read(stream));
            case 5:
                return new ControllerException.StorageException(
                    FfiConverterString.INSTANCE.Read(stream));
            case 6:
                return new ControllerException.InvalidInput(
                    FfiConverterString.INSTANCE.Read(stream));
            case 7:
                return new ControllerException.DisconnectException(
                    FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeControllerError.Read()", value));
        }
    }

    public override int AllocationSize(ControllerException value) {
        switch (value) {

            case ControllerException.InitializationException variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);

            case ControllerException.SignupException variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);

            case ControllerException.ExecutionException variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);

            case ControllerException.NetworkException variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);

            case ControllerException.StorageException variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);

            case ControllerException.InvalidInput variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);

            case ControllerException.DisconnectException variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@v1);
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeControllerError.AllocationSize()", value));
        }
    }

    public override void Write(ControllerException value, BigEndianStream stream) {
        switch (value) {
            case ControllerException.InitializationException variant_value:
                stream.WriteInt(1);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            case ControllerException.SignupException variant_value:
                stream.WriteInt(2);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            case ControllerException.ExecutionException variant_value:
                stream.WriteInt(3);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            case ControllerException.NetworkException variant_value:
                stream.WriteInt(4);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            case ControllerException.StorageException variant_value:
                stream.WriteInt(5);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            case ControllerException.InvalidInput variant_value:
                stream.WriteInt(6);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            case ControllerException.DisconnectException variant_value:
                stream.WriteInt(7);
                FfiConverterString.INSTANCE.Write(variant_value.@v1, stream);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeControllerError.Write()", value));
        }
    }
}




class FfiConverterSequenceString: FfiConverterRustBuffer<string[]> {
    public static FfiConverterSequenceString INSTANCE = new FfiConverterSequenceString();

    public override string[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new string[(length)];
        var readFn = FfiConverterString.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(string[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(string[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterString.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */


#pragma warning restore 8625
internal static class ControllerUniffiMethods {
    public static string FormatCall(Call @call) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_controller_uniffi_fn_func_format_call(FfiConverterTypeCall.INSTANCE.Lower(@call), ref _status)
));
    }


    /// <exception cref="ControllerException"></exception>
    public static bool ValidateFelt(string @felt) {
        return FfiConverterBoolean.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeControllerError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_controller_uniffi_fn_func_validate_felt(FfiConverterString.INSTANCE.Lower(@felt), ref _status)
));
    }


}

