// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import nativeModule, {
  type UniffiRustFutureContinuationCallback,
  type UniffiForeignFutureDroppedCallback,
  type UniffiForeignFutureDroppedCallbackStruct,
  type UniffiForeignFutureResultU8,
  type UniffiForeignFutureCompleteU8,
  type UniffiForeignFutureResultI8,
  type UniffiForeignFutureCompleteI8,
  type UniffiForeignFutureResultU16,
  type UniffiForeignFutureCompleteU16,
  type UniffiForeignFutureResultI16,
  type UniffiForeignFutureCompleteI16,
  type UniffiForeignFutureResultU32,
  type UniffiForeignFutureCompleteU32,
  type UniffiForeignFutureResultI32,
  type UniffiForeignFutureCompleteI32,
  type UniffiForeignFutureResultU64,
  type UniffiForeignFutureCompleteU64,
  type UniffiForeignFutureResultI64,
  type UniffiForeignFutureCompleteI64,
  type UniffiForeignFutureResultF32,
  type UniffiForeignFutureCompleteF32,
  type UniffiForeignFutureResultF64,
  type UniffiForeignFutureCompleteF64,
  type UniffiForeignFutureResultRustBuffer,
  type UniffiForeignFutureCompleteRustBuffer,
  type UniffiForeignFutureResultVoid,
  type UniffiForeignFutureCompleteVoid,
} from "./controller-ffi";
import {
  type FfiConverter, 
  type UniffiByteArray, 
  type UniffiObjectFactory, 
  type UniffiRustArcPtr, 
  type UnsafeMutableRawPointer, 
  AbstractFfiConverterByteArray, 
  FfiConverterArray, 
  FfiConverterBool, 
  FfiConverterInt32, 
  FfiConverterObject, 
  FfiConverterOptional, 
  FfiConverterUInt64, 
  RustBuffer, 
  UniffiAbstractObject, 
  UniffiError, 
  UniffiInternalError, 
  UniffiRustCaller, 
  destructorGuardSymbol, 
  pointerLiteralSymbol, 
  uniffiCreateFfiConverterString, 
  uniffiCreateRecord, 
  uniffiTypeNameSymbol, 
  variantOrdinalSymbol } from "uniffi-bindgen-react-native";

// Get converters from the other files, if any.
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  false;
// Public interface members begin here.

export function controllerHasStorage(appId: string): boolean /*throws*/ {
    return FfiConverterBool.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_func_controller_has_storage(
        FfiConverterString.lower(appId),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
export function getControllerClassHash(version: Version): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_func_get_controller_class_hash(
        FfiConverterTypeVersion.lower(version),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
export function getPublicKey(privateKey: FieldElement): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_func_get_public_key(
        FfiConverterTypeFieldElement.lower(privateKey),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
export function signerToGuid(privateKey: FieldElement): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_func_signer_to_guid(
        FfiConverterTypeFieldElement.lower(privateKey),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
export function validateFelt(felt: string): boolean /*throws*/ {
    return FfiConverterBool.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_func_validate_felt(
        FfiConverterString.lower(felt),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }






export type Call = {
    contractAddress: FieldElement,
    entrypoint: string,
    calldata: Array<FieldElement>
}

/**
 * Generated factory for {@link Call} record objects.
 */
export const Call = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<Call, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        /**
         * Create a frozen instance of {@link Call}, with defaults specified
         * in Rust, in the {@link controller} crate.
         */
        create,

        /**
         * Create a frozen instance of {@link Call}, with defaults specified
         * in Rust, in the {@link controller} crate.
         */
        new: create,

        /**
         * Defaults specified in the {@link controller} crate.
         */
        defaults: () => Object.freeze(defaults()) as Partial<Call>,
    });
})();

const FfiConverterTypeCall = (() => {
    type TypeName = Call;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                contractAddress: FfiConverterTypeFieldElement.read(from), 
                entrypoint: FfiConverterString.read(from), 
                calldata: FfiConverterArrayTypeFieldElement.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterTypeFieldElement.write(value.contractAddress, into);
            FfiConverterString.write(value.entrypoint, into);
            FfiConverterArrayTypeFieldElement.write(value.calldata, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterTypeFieldElement.allocationSize(value.contractAddress) + 
            FfiConverterString.allocationSize(value.entrypoint) + 
            FfiConverterArrayTypeFieldElement.allocationSize(value.calldata);
            
        }
    };
    return new FFIConverter();
})();


export type SessionPolicies = {
    policies: Array<SessionPolicy>,
    maxFee: FieldElement
}

/**
 * Generated factory for {@link SessionPolicies} record objects.
 */
export const SessionPolicies = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<SessionPolicies, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        /**
         * Create a frozen instance of {@link SessionPolicies}, with defaults specified
         * in Rust, in the {@link controller} crate.
         */
        create,

        /**
         * Create a frozen instance of {@link SessionPolicies}, with defaults specified
         * in Rust, in the {@link controller} crate.
         */
        new: create,

        /**
         * Defaults specified in the {@link controller} crate.
         */
        defaults: () => Object.freeze(defaults()) as Partial<SessionPolicies>,
    });
})();

const FfiConverterTypeSessionPolicies = (() => {
    type TypeName = SessionPolicies;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                policies: FfiConverterArrayTypeSessionPolicy.read(from), 
                maxFee: FfiConverterTypeFieldElement.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterArrayTypeSessionPolicy.write(value.policies, into);
            FfiConverterTypeFieldElement.write(value.maxFee, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterArrayTypeSessionPolicy.allocationSize(value.policies) + 
            FfiConverterTypeFieldElement.allocationSize(value.maxFee);
            
        }
    };
    return new FFIConverter();
})();


export type SessionPolicy = {
    contractAddress: FieldElement,
    entrypoint: string
}

/**
 * Generated factory for {@link SessionPolicy} record objects.
 */
export const SessionPolicy = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<SessionPolicy, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        /**
         * Create a frozen instance of {@link SessionPolicy}, with defaults specified
         * in Rust, in the {@link controller} crate.
         */
        create,

        /**
         * Create a frozen instance of {@link SessionPolicy}, with defaults specified
         * in Rust, in the {@link controller} crate.
         */
        new: create,

        /**
         * Defaults specified in the {@link controller} crate.
         */
        defaults: () => Object.freeze(defaults()) as Partial<SessionPolicy>,
    });
})();

const FfiConverterTypeSessionPolicy = (() => {
    type TypeName = SessionPolicy;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            return {
                contractAddress: FfiConverterTypeFieldElement.read(from), 
                entrypoint: FfiConverterString.read(from)
            };
        }
        write(value: TypeName, into: RustBuffer): void {
            FfiConverterTypeFieldElement.write(value.contractAddress, into);
            FfiConverterString.write(value.entrypoint, into);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterTypeFieldElement.allocationSize(value.contractAddress) + 
            FfiConverterString.allocationSize(value.entrypoint);
            
        }
    };
    return new FFIConverter();
})();


const stringConverter = {
    stringToBytes: (s: string) =>
        uniffiCaller.rustCall((status) => nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_arraybuffer(s, status)),
    bytesToString: (ab: UniffiByteArray) =>
        uniffiCaller.rustCall((status) => nativeModule().ubrn_uniffi_internal_fn_func_ffi__arraybuffer_to_string(ab, status)),
    stringByteLength: (s: string) =>
        uniffiCaller.rustCall((status) => nativeModule().ubrn_uniffi_internal_fn_func_ffi__string_to_byte_length(s, status)),
};
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);




/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
export type FieldElement = string;
// FfiConverter for FieldElement, a type alias for string.
const FfiConverterTypeFieldElement = FfiConverterString;



// Flat error type: ControllerError
export enum ControllerError_Tags {
    InitializationError = "InitializationError",
    SignupError = "SignupError",
    ExecutionError = "ExecutionError",
    NetworkError = "NetworkError",
    StorageError = "StorageError",
    InvalidInput = "InvalidInput",
    DisconnectError = "DisconnectError"
}
export const ControllerError = (() => {
    class InitializationError extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 1;

        public readonly tag = ControllerError_Tags.InitializationError;

        constructor(message: string) {
            super("ControllerError", "InitializationError", message);
        }

        static instanceOf(e: any): e is InitializationError {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 1
            );
        }
    }
    class SignupError extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 2;

        public readonly tag = ControllerError_Tags.SignupError;

        constructor(message: string) {
            super("ControllerError", "SignupError", message);
        }

        static instanceOf(e: any): e is SignupError {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 2
            );
        }
    }
    class ExecutionError extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 3;

        public readonly tag = ControllerError_Tags.ExecutionError;

        constructor(message: string) {
            super("ControllerError", "ExecutionError", message);
        }

        static instanceOf(e: any): e is ExecutionError {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 3
            );
        }
    }
    class NetworkError extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 4;

        public readonly tag = ControllerError_Tags.NetworkError;

        constructor(message: string) {
            super("ControllerError", "NetworkError", message);
        }

        static instanceOf(e: any): e is NetworkError {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 4
            );
        }
    }
    class StorageError extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 5;

        public readonly tag = ControllerError_Tags.StorageError;

        constructor(message: string) {
            super("ControllerError", "StorageError", message);
        }

        static instanceOf(e: any): e is StorageError {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 5
            );
        }
    }
    class InvalidInput extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 6;

        public readonly tag = ControllerError_Tags.InvalidInput;

        constructor(message: string) {
            super("ControllerError", "InvalidInput", message);
        }

        static instanceOf(e: any): e is InvalidInput {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 6
            );
        }
    }
    class DisconnectError extends UniffiError {
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [uniffiTypeNameSymbol]: string = "ControllerError";
        /**
         * @private
         * This field is private and should not be used.
         */
        readonly [variantOrdinalSymbol] = 7;

        public readonly tag = ControllerError_Tags.DisconnectError;

        constructor(message: string) {
            super("ControllerError", "DisconnectError", message);
        }

        static instanceOf(e: any): e is DisconnectError {
            return (
                instanceOf(e) && (e as any)[variantOrdinalSymbol] === 7
            );
        }
    }

    // Utility function which does not rely on instanceof.
    function instanceOf(e: any): e is ControllerError {
        return (e as any)[uniffiTypeNameSymbol] === "ControllerError";
    }
    return {
        InitializationError,
        SignupError,
        ExecutionError,
        NetworkError,
        StorageError,
        InvalidInput,
        DisconnectError,
        instanceOf,
    };
})();

// Union type for ControllerError error type.


export type ControllerError = InstanceType<
    typeof ControllerError[keyof Omit<typeof ControllerError, 'instanceOf'>]
>;

const FfiConverterTypeControllerError = (() => {
    const intConverter = FfiConverterInt32;
    type TypeName = ControllerError;
    class FfiConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (intConverter.read(from)) {
                case 1: return new ControllerError.InitializationError(FfiConverterString.read(from)
                );
            
                case 2: return new ControllerError.SignupError(FfiConverterString.read(from)
                );
            
                case 3: return new ControllerError.ExecutionError(FfiConverterString.read(from)
                );
            
                case 4: return new ControllerError.NetworkError(FfiConverterString.read(from)
                );
            
                case 5: return new ControllerError.StorageError(FfiConverterString.read(from)
                );
            
                case 6: return new ControllerError.InvalidInput(FfiConverterString.read(from)
                );
            
                case 7: return new ControllerError.DisconnectError(FfiConverterString.read(from)
                );
            
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            const obj = value as any;
            const index = obj[variantOrdinalSymbol] as number;
            intConverter.write(index, into);
        }
        allocationSize(value: TypeName): number {
            return intConverter.allocationSize(0);
        }
    }
    return new FfiConverter();
})();


export enum SignerType {
    Webauthn,
    Starknet
}

const FfiConverterTypeSignerType = (() => {
    const ordinalConverter = FfiConverterInt32;
    type TypeName = SignerType;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (ordinalConverter.read(from)) {
                case 1: return SignerType.Webauthn;
                case 2: return SignerType.Starknet;
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            switch (value) {
                case SignerType.Webauthn: return ordinalConverter.write(1, into);
                case SignerType.Starknet: return ordinalConverter.write(2, into);
            }
        }
        allocationSize(value: TypeName): number {
            return ordinalConverter.allocationSize(0);
        }
    }
    return new FFIConverter();
})();





export enum Version {
    V104,
    V105,
    V106,
    V107,
    V108,
    V109,
    Latest
}

const FfiConverterTypeVersion = (() => {
    const ordinalConverter = FfiConverterInt32;
    type TypeName = Version;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        read(from: RustBuffer): TypeName {
            switch (ordinalConverter.read(from)) {
                case 1: return Version.V104;
                case 2: return Version.V105;
                case 3: return Version.V106;
                case 4: return Version.V107;
                case 5: return Version.V108;
                case 6: return Version.V109;
                case 7: return Version.Latest;
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        write(value: TypeName, into: RustBuffer): void {
            switch (value) {
                case Version.V104: return ordinalConverter.write(1, into);
                case Version.V105: return ordinalConverter.write(2, into);
                case Version.V106: return ordinalConverter.write(3, into);
                case Version.V107: return ordinalConverter.write(4, into);
                case Version.V108: return ordinalConverter.write(5, into);
                case Version.V109: return ordinalConverter.write(6, into);
                case Version.Latest: return ordinalConverter.write(7, into);
            }
        }
        allocationSize(value: TypeName): number {
            return ordinalConverter.allocationSize(0);
        }
    }
    return new FFIConverter();
})();





export interface ControllerInterface {
    
    address()  /*throws*/: FieldElement;
    appId()  /*throws*/: string;
    chainId()  /*throws*/: FieldElement;
    clearLastError() : void;
    delegateAccount()  /*throws*/: FieldElement;
    disconnect()  /*throws*/: void;
    errorMessage()  /*throws*/: string;
    execute(calls: Array<Call>)  /*throws*/: FieldElement;
    signup(signerType: SignerType, sessionExpiration: /*u64*/bigint | undefined, cartridgeApiUrl: string | undefined)  /*throws*/: void;
    switchChain(rpcUrl: string)  /*throws*/: void;
    transfer(recipient: FieldElement, amount: FieldElement)  /*throws*/: FieldElement;
    username()  /*throws*/: string;
}


export class Controller extends UniffiAbstractObject implements ControllerInterface {

    readonly [uniffiTypeNameSymbol] = "Controller";
    readonly [destructorGuardSymbol]: UniffiRustArcPtr;
    readonly [pointerLiteralSymbol]: UnsafeMutableRawPointer;
    constructor(appId: string, username: string, classHash: FieldElement, rpcUrl: string, owner: OwnerInterface, address: FieldElement, chainId: FieldElement) /*throws*/ {
        super();
        const pointer =
            
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_constructor_controller_new(
        FfiConverterString.lower(appId),
        FfiConverterString.lower(username),
        FfiConverterTypeFieldElement.lower(classHash),
        FfiConverterString.lower(rpcUrl),
        FfiConverterTypeOwner.lower(owner),
        FfiConverterTypeFieldElement.lower(address),
        FfiConverterTypeFieldElement.lower(chainId),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
        this[pointerLiteralSymbol] = pointer;
        this[destructorGuardSymbol] = uniffiTypeControllerObjectFactory.bless(pointer);
    }

    
public static fromStorage(appId: string): ControllerInterface /*throws*/ {
    return FfiConverterTypeController.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_constructor_controller_from_storage(
        FfiConverterString.lower(appId),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public static newHeadless(appId: string, username: string, classHash: FieldElement, rpcUrl: string, owner: OwnerInterface, chainId: FieldElement): ControllerInterface /*throws*/ {
    return FfiConverterTypeController.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_constructor_controller_new_headless(
        FfiConverterString.lower(appId),
        FfiConverterString.lower(username),
        FfiConverterTypeFieldElement.lower(classHash),
        FfiConverterString.lower(rpcUrl),
        FfiConverterTypeOwner.lower(owner),
        FfiConverterTypeFieldElement.lower(chainId),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    

    
public address(): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_address(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public appId(): string /*throws*/ {
    return FfiConverterString.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_app_id(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public chainId(): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_chain_id(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public clearLastError(): void {uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => { nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_clear_last_error(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
    }
    
public delegateAccount(): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_delegate_account(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public disconnect(): void /*throws*/ {
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => { nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_disconnect(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
    }
    
public errorMessage(): string /*throws*/ {
    return FfiConverterString.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_error_message(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public execute(calls: Array<Call>): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_execute(uniffiTypeControllerObjectFactory.clonePointer(this), 
        FfiConverterArrayTypeCall.lower(calls),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public signup(signerType: SignerType, sessionExpiration: /*u64*/bigint | undefined, cartridgeApiUrl: string | undefined): void /*throws*/ {
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => { nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_signup(uniffiTypeControllerObjectFactory.clonePointer(this), 
        FfiConverterTypeSignerType.lower(signerType),
        FfiConverterOptionalUInt64.lower(sessionExpiration),
        FfiConverterOptionalString.lower(cartridgeApiUrl),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
    }
    
public switchChain(rpcUrl: string): void /*throws*/ {
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => { nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_switch_chain(uniffiTypeControllerObjectFactory.clonePointer(this), 
        FfiConverterString.lower(rpcUrl),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
    }
    
public transfer(recipient: FieldElement, amount: FieldElement): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_transfer(uniffiTypeControllerObjectFactory.clonePointer(this), 
        FfiConverterTypeFieldElement.lower(recipient),
        FfiConverterTypeFieldElement.lower(amount),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public username(): string /*throws*/ {
    return FfiConverterString.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_controller_username(uniffiTypeControllerObjectFactory.clonePointer(this), 
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    

    /**
     * {@inheritDoc uniffi-bindgen-react-native#UniffiAbstractObject.uniffiDestroy}
     */
    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeControllerObjectFactory.pointer(this);
            uniffiTypeControllerObjectFactory.freePointer(pointer);
            uniffiTypeControllerObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj: any): obj is Controller {
        return uniffiTypeControllerObjectFactory.isConcreteType(obj);
    }

    
}

const uniffiTypeControllerObjectFactory: UniffiObjectFactory<ControllerInterface> = (() => {
    
    return {
    create(pointer: UnsafeMutableRawPointer): ControllerInterface {
        const instance = Object.create(Controller.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "Controller";
        return instance;
    },

    
    bless(p: UnsafeMutableRawPointer): UniffiRustArcPtr {
        return uniffiCaller.rustCall(
            /*caller:*/ (status) =>
                nativeModule().ubrn_ffi_Controller__bless_pointer(p, status),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    unbless(ptr: UniffiRustArcPtr) {
        ptr.markDestroyed();
    },

    pointer(obj: ControllerInterface): UnsafeMutableRawPointer {
        if ((obj as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj as any)[pointerLiteralSymbol];
    },

    clonePointer(obj: ControllerInterface): UnsafeMutableRawPointer {
        const pointer = this.pointer(obj);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_controller_uniffi_fn_clone_controller(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UnsafeMutableRawPointer): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_controller_uniffi_fn_free_controller(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj: any): obj is ControllerInterface {
        return obj[destructorGuardSymbol] && obj[uniffiTypeNameSymbol] === "Controller";
    },
}})();
// FfiConverter for ControllerInterface
const FfiConverterTypeController =  new FfiConverterObject(uniffiTypeControllerObjectFactory);


export interface OwnerInterface {
    
}


export class Owner extends UniffiAbstractObject implements OwnerInterface {

    readonly [uniffiTypeNameSymbol] = "Owner";
    readonly [destructorGuardSymbol]: UniffiRustArcPtr;
    readonly [pointerLiteralSymbol]: UnsafeMutableRawPointer;
    constructor(privateKey: string) /*throws*/ {
        super();
        const pointer =
            
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_constructor_owner_new(
        FfiConverterString.lower(privateKey),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
        this[pointerLiteralSymbol] = pointer;
        this[destructorGuardSymbol] = uniffiTypeOwnerObjectFactory.bless(pointer);
    }

    

    

    /**
     * {@inheritDoc uniffi-bindgen-react-native#UniffiAbstractObject.uniffiDestroy}
     */
    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeOwnerObjectFactory.pointer(this);
            uniffiTypeOwnerObjectFactory.freePointer(pointer);
            uniffiTypeOwnerObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj: any): obj is Owner {
        return uniffiTypeOwnerObjectFactory.isConcreteType(obj);
    }

    
}

const uniffiTypeOwnerObjectFactory: UniffiObjectFactory<OwnerInterface> = (() => {
    
    return {
    create(pointer: UnsafeMutableRawPointer): OwnerInterface {
        const instance = Object.create(Owner.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "Owner";
        return instance;
    },

    
    bless(p: UnsafeMutableRawPointer): UniffiRustArcPtr {
        return uniffiCaller.rustCall(
            /*caller:*/ (status) =>
                nativeModule().ubrn_ffi_Owner__bless_pointer(p, status),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    unbless(ptr: UniffiRustArcPtr) {
        ptr.markDestroyed();
    },

    pointer(obj: OwnerInterface): UnsafeMutableRawPointer {
        if ((obj as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj as any)[pointerLiteralSymbol];
    },

    clonePointer(obj: OwnerInterface): UnsafeMutableRawPointer {
        const pointer = this.pointer(obj);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_controller_uniffi_fn_clone_owner(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UnsafeMutableRawPointer): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_controller_uniffi_fn_free_owner(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj: any): obj is OwnerInterface {
        return obj[destructorGuardSymbol] && obj[uniffiTypeNameSymbol] === "Owner";
    },
}})();
// FfiConverter for OwnerInterface
const FfiConverterTypeOwner =  new FfiConverterObject(uniffiTypeOwnerObjectFactory);


export interface SessionAccountInterface {
    
    execute(calls: Array<Call>)  /*throws*/: FieldElement;
    executeFromOutside(calls: Array<Call>)  /*throws*/: FieldElement;
}


export class SessionAccount extends UniffiAbstractObject implements SessionAccountInterface {

    readonly [uniffiTypeNameSymbol] = "SessionAccount";
    readonly [destructorGuardSymbol]: UniffiRustArcPtr;
    readonly [pointerLiteralSymbol]: UnsafeMutableRawPointer;
    constructor(rpcUrl: string, privateKey: string, address: FieldElement, ownerGuid: FieldElement, chainId: FieldElement, policies: SessionPolicies, sessionExpiration: /*u64*/bigint) /*throws*/ {
        super();
        const pointer =
            
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_constructor_sessionaccount_new(
        FfiConverterString.lower(rpcUrl),
        FfiConverterString.lower(privateKey),
        FfiConverterTypeFieldElement.lower(address),
        FfiConverterTypeFieldElement.lower(ownerGuid),
        FfiConverterTypeFieldElement.lower(chainId),
        FfiConverterTypeSessionPolicies.lower(policies),
        FfiConverterUInt64.lower(sessionExpiration),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    );
        this[pointerLiteralSymbol] = pointer;
        this[destructorGuardSymbol] = uniffiTypeSessionAccountObjectFactory.bless(pointer);
    }

    
public static createFromSubscribe(privateKey: string, policies: SessionPolicies, rpcUrl: string, cartridgeApiUrl: string): SessionAccountInterface /*throws*/ {
    return FfiConverterTypeSessionAccount.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_constructor_sessionaccount_create_from_subscribe(
        FfiConverterString.lower(privateKey),
        FfiConverterTypeSessionPolicies.lower(policies),
        FfiConverterString.lower(rpcUrl),
        FfiConverterString.lower(cartridgeApiUrl),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    

    
public execute(calls: Array<Call>): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_sessionaccount_execute(uniffiTypeSessionAccountObjectFactory.clonePointer(this), 
        FfiConverterArrayTypeCall.lower(calls),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    
public executeFromOutside(calls: Array<Call>): FieldElement /*throws*/ {
    return FfiConverterTypeFieldElement.lift(
        uniffiCaller.rustCallWithError(
            /*liftError:*/ FfiConverterTypeControllerError.lift.bind(FfiConverterTypeControllerError),
            /*caller:*/ (callStatus) => {
                return nativeModule().ubrn_uniffi_controller_uniffi_fn_method_sessionaccount_execute_from_outside(uniffiTypeSessionAccountObjectFactory.clonePointer(this), 
        FfiConverterArrayTypeCall.lower(calls),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift,
    ));
    }
    

    /**
     * {@inheritDoc uniffi-bindgen-react-native#UniffiAbstractObject.uniffiDestroy}
     */
    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeSessionAccountObjectFactory.pointer(this);
            uniffiTypeSessionAccountObjectFactory.freePointer(pointer);
            uniffiTypeSessionAccountObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj: any): obj is SessionAccount {
        return uniffiTypeSessionAccountObjectFactory.isConcreteType(obj);
    }

    
}

const uniffiTypeSessionAccountObjectFactory: UniffiObjectFactory<SessionAccountInterface> = (() => {
    
    return {
    create(pointer: UnsafeMutableRawPointer): SessionAccountInterface {
        const instance = Object.create(SessionAccount.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "SessionAccount";
        return instance;
    },

    
    bless(p: UnsafeMutableRawPointer): UniffiRustArcPtr {
        return uniffiCaller.rustCall(
            /*caller:*/ (status) =>
                nativeModule().ubrn_ffi_SessionAccount__bless_pointer(p, status),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    unbless(ptr: UniffiRustArcPtr) {
        ptr.markDestroyed();
    },

    pointer(obj: SessionAccountInterface): UnsafeMutableRawPointer {
        if ((obj as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj as any)[pointerLiteralSymbol];
    },

    clonePointer(obj: SessionAccountInterface): UnsafeMutableRawPointer {
        const pointer = this.pointer(obj);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_controller_uniffi_fn_clone_sessionaccount(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UnsafeMutableRawPointer): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().ubrn_uniffi_controller_uniffi_fn_free_sessionaccount(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj: any): obj is SessionAccountInterface {
        return obj[destructorGuardSymbol] && obj[uniffiTypeNameSymbol] === "SessionAccount";
    },
}})();
// FfiConverter for SessionAccountInterface
const FfiConverterTypeSessionAccount =  new FfiConverterObject(uniffiTypeSessionAccountObjectFactory);


// FfiConverter for string | undefined
const FfiConverterOptionalString = new FfiConverterOptional(FfiConverterString);


// FfiConverter for /*u64*/bigint | undefined
const FfiConverterOptionalUInt64 = new FfiConverterOptional(FfiConverterUInt64);


// FfiConverter for Array<Call>
const FfiConverterArrayTypeCall = new FfiConverterArray(FfiConverterTypeCall);


// FfiConverter for Array<SessionPolicy>
const FfiConverterArrayTypeSessionPolicy = new FfiConverterArray(FfiConverterTypeSessionPolicy);


// FfiConverter for Array<FieldElement>
const FfiConverterArrayTypeFieldElement = new FfiConverterArray(FfiConverterTypeFieldElement);

/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
    // Get the bindings contract version from our ComponentInterface
    const bindingsContractVersion = 30;
    // Get the scaffolding contract version by calling the into the dylib
    const scaffoldingContractVersion = nativeModule().ubrn_ffi_controller_uniffi_uniffi_contract_version();
    if (bindingsContractVersion !== scaffoldingContractVersion) {
        throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_func_controller_has_storage() !== 40864) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_func_controller_has_storage");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_func_get_controller_class_hash() !== 11028) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_func_get_controller_class_hash");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_func_get_public_key() !== 36036) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_func_get_public_key");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_func_signer_to_guid() !== 34619) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_func_signer_to_guid");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_func_validate_felt() !== 45886) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_func_validate_felt");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_address() !== 58142) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_address");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_app_id() !== 56550) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_app_id");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_chain_id() !== 39031) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_chain_id");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_clear_last_error() !== 47063) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_clear_last_error");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_delegate_account() !== 31461) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_delegate_account");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_disconnect() !== 25464) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_disconnect");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_error_message() !== 27332) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_error_message");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_execute() !== 41685) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_execute");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_signup() !== 53849) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_signup");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_switch_chain() !== 37555) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_switch_chain");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_transfer() !== 64142) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_transfer");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_controller_username() !== 5497) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_controller_username");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_sessionaccount_execute() !== 61492) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_sessionaccount_execute");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_method_sessionaccount_execute_from_outside() !== 27820) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_method_sessionaccount_execute_from_outside");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_constructor_controller_from_storage() !== 39320) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_constructor_controller_from_storage");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_constructor_controller_new() !== 18866) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_constructor_controller_new");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_constructor_controller_new_headless() !== 44171) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_constructor_controller_new_headless");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_constructor_owner_new() !== 62973) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_constructor_owner_new");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_constructor_sessionaccount_create_from_subscribe() !== 29386) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_constructor_sessionaccount_create_from_subscribe");
    }
    if (nativeModule().ubrn_uniffi_controller_uniffi_checksum_constructor_sessionaccount_new() !== 1841) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_controller_uniffi_checksum_constructor_sessionaccount_new");
    }

    }

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeCall,
    FfiConverterTypeController,
    FfiConverterTypeControllerError,
    FfiConverterTypeFieldElement,
    FfiConverterTypeOwner,
    FfiConverterTypeSessionAccount,
    FfiConverterTypeSessionPolicies,
    FfiConverterTypeSessionPolicy,
    FfiConverterTypeSignerType,
    FfiConverterTypeVersion,
  }
});