// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#include "../cpp/controller.h"
#endif

#import <React/RCTBridgeModule.h>

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCommon/RCTTurboModule.h>
#endif

@interface Controller : NSObject <RCTBridgeModule>

#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params;
#endif

@end
