// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#include "../cpp/dojo.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import <ArcadeNativeSpec/ArcadeNativeSpec.h>

@interface Dojo : NSObject <NativeDojoSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Dojo : NSObject <RCTBridgeModule>
#endif

@end