// Generated by uniffi-bindgen-react-native
import installer from './NativeController';

// Register the rust crate with the JSI runtime
console.log('🔍 Checking Controller native module...');
console.log('Controller installer:', installer);

// Check if module is available
const controllerAvailable = installer && typeof installer.installRustCrate === 'function';
console.log('Controller available:', controllerAvailable);

if (!controllerAvailable) {
  throw new Error('❌ CRITICAL: Controller native module not found! Make sure the build completed successfully.');
}

try {
  console.log('⚙️ Installing Controller crate...');
  const controllerResult = installer.installRustCrate();
  console.log('✅ Controller crate installed, result:', controllerResult);
  
  // Check if global.NativeController is now available
  const hasNativeController = typeof (globalThis as any).NativeController !== 'undefined';
  console.log('globalThis.NativeController available:', hasNativeController);
  if (hasNativeController) {
    console.log('NativeController keys:', Object.keys((globalThis as any).NativeController || {}).slice(0, 5));
  }
} catch (e) {
  console.error('❌ Error installing Controller:', e);
  throw e;
}

console.log('✅ Controller Rust crate installed successfully!');

// NOW it's safe to import the generated bindings
// Export the generated bindings to the app.
export * from './controller';

// Now import the bindings so we can initialize them
import * as controller from './controller';

// Initialize the generated bindings
let initialized = false;
if (!initialized) {
  controller.default.initialize();
  initialized = true;
}

// Export the controller as default
export default {
  controller,
};

