// Generated by uniffi-bindgen-react-native
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry, NativeModules, Platform } from 'react-native';

export interface Spec extends TurboModule {
  installRustCrate(): boolean;
  cleanupRustCrate(): boolean;
}

console.log('=== NativeController Debug ===');
console.log('Platform:', Platform.OS);

// Debug what's available
const turboModule = TurboModuleRegistry.get<Spec>('Controller');
console.log('TurboModuleRegistry.get("Controller"):', turboModule);
console.log('TurboModule type:', typeof turboModule);
if (turboModule) {
  console.log('TurboModule keys:', Object.keys(turboModule));
  console.log('TurboModule.installRustCrate:', turboModule.installRustCrate);
}

console.log('NativeModules:', Object.keys(NativeModules));
const bridgeModule = NativeModules.Controller;
console.log('NativeModules.Controller:', bridgeModule);
if (bridgeModule) {
  console.log('BridgeModule type:', typeof bridgeModule);
  console.log('BridgeModule keys:', Object.keys(bridgeModule));
  console.log('BridgeModule.installRustCrate:', bridgeModule.installRustCrate);
}

// On iOS, TurboModuleRegistry works perfectly
// On Android with New Architecture, we need to handle it differently
let ControllerModule: Spec | null = null;

if (Platform.OS === 'ios') {
  ControllerModule = TurboModuleRegistry.getEnforcing<Spec>('Controller');
} else {
  // Android: The module might be returned as a proxy object
  // Try TurboModuleRegistry first
  if (turboModule && typeof turboModule.installRustCrate === 'function') {
    console.log('Using TurboModule');
    ControllerModule = turboModule;
  } else if (bridgeModule && typeof bridgeModule.installRustCrate === 'function') {
    console.log('Using NativeModules bridge');
    ControllerModule = bridgeModule as Spec;
  }
}

if (!ControllerModule) {
  console.error('=== Controller module NOT found! ===');
  throw new Error(
    `Controller native module is not available. ` +
    `Platform: ${Platform.OS}. ` +
    `Make sure the native code is properly linked.`
  );
}

console.log('=== Controller module found! ===');
export default ControllerModule;
