// Generated by uniffi-bindgen-react-native
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry, NativeModules, Platform } from 'react-native';

export interface Spec extends TurboModule {
  installRustCrate(): boolean;
  cleanupRustCrate(): boolean;
}

console.log('=== NativeController Debug ===');
console.log('Platform:', Platform.OS);

// Debug what's available
const turboModule = TurboModuleRegistry.get<Spec>('Controller');
console.log('TurboModuleRegistry.get("Controller"):', turboModule);
console.log('TurboModule type:', typeof turboModule);
if (turboModule) {
  console.log('TurboModule keys:', Object.keys(turboModule));
  console.log('TurboModule.installRustCrate:', turboModule.installRustCrate);
}

console.log('NativeModules keys:', Object.keys(NativeModules));
const bridgeModule = NativeModules.Controller;
console.log('NativeModules.Controller:', bridgeModule);
if (bridgeModule) {
  console.log('BridgeModule type:', typeof bridgeModule);
  console.log('BridgeModule keys:', Object.keys(bridgeModule));
  console.log('BridgeModule.installRustCrate:', bridgeModule.installRustCrate);
}

// Determine which module to use
let ControllerModule: Spec | null = null;

if (Platform.OS === 'ios') {
  // iOS uses TurboModule
  ControllerModule = TurboModuleRegistry.getEnforcing<Spec>('Controller');
} else if (Platform.OS === 'android') {
  // Android: Try TurboModule first, then fallback to bridge
  if (turboModule && typeof turboModule.installRustCrate === 'function') {
    console.log('Using TurboModule on Android');
    ControllerModule = turboModule;
  } else if (bridgeModule && typeof bridgeModule.installRustCrate === 'function') {
    console.log('Using NativeModules bridge on Android');
    ControllerModule = bridgeModule as Spec;
  } else if (bridgeModule) {
    // The module exists but methods might be accessed differently
    console.log('Bridge module exists, attempting to use it');
    ControllerModule = bridgeModule as Spec;
  }
}

if (!ControllerModule) {
  console.error('=== Controller module NOT found! ===');
  console.error('Available NativeModules:', Object.keys(NativeModules));
  throw new Error(
    `Controller native module is not available. ` +
    `Platform: ${Platform.OS}. ` +
    `Available modules: ${Object.keys(NativeModules).join(', ')}. ` +
    `Make sure the native code is properly linked.`
  );
}

console.log('=== Controller module found! ===');
export default ControllerModule;
