# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_controller_uniffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_controller_uniffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_controller_uniffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("controller_uniffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_controller_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_controller_uniffi_checksum_func_controller_has_storage() != 61615:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_func_get_controller_class_hash() != 56956:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_func_get_public_key() != 22101:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_func_signer_to_guid() != 11653:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_func_validate_felt() != 48416:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_constructor_controller_from_storage() != 50686:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_constructor_controller_new() != 42904:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_constructor_controller_new_headless() != 60496:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_address() != 42791:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_app_id() != 56599:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_chain_id() != 21637:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_clear_last_error() != 7520:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_delegate_account() != 65360:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_disconnect() != 64757:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_error_message() != 34844:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_execute() != 10797:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_signup() != 58043:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_switch_chain() != 24689:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_transfer() != 27607:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_controller_username() != 45760:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_constructor_owner_new() != 39425:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_constructor_sessionaccount_create_from_subscribe() != 27716:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_constructor_sessionaccount_new() != 6297:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_sessionaccount_execute() != 16497:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_controller_uniffi_checksum_method_sessionaccount_execute_from_outside() != 6895:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_controller_uniffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_controller_uniffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_controller_uniffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rustbuffer_free.restype = None
_UniffiLib.ffi_controller_uniffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFutureDroppedCallbackStruct(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK),
    ]
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u8.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_controller_uniffi_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_u8.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i8.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_controller_uniffi_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_i8.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u16.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_controller_uniffi_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_u16.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i16.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_controller_uniffi_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_i16.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_controller_uniffi_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_u32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_controller_uniffi_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_i32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_u64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_controller_uniffi_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_u64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_i64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_controller_uniffi_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_i64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_f32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_controller_uniffi_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_f32.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_f64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_controller_uniffi_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_f64.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_controller_uniffi_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_poll_void.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_cancel_void.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_controller_uniffi_rust_future_complete_void.restype = None
_UniffiLib.ffi_controller_uniffi_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_controller_uniffi_rust_future_free_void.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_clone_controller.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_clone_controller.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_free_controller.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_free_controller.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_clone_owner.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_clone_owner.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_free_owner.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_free_owner.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_clone_sessionaccount.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_clone_sessionaccount.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_free_sessionaccount.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_free_sessionaccount.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_func_controller_has_storage.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_func_controller_has_storage.restype = ctypes.c_int8
_UniffiLib.uniffi_controller_uniffi_fn_func_get_controller_class_hash.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_func_get_controller_class_hash.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_func_get_public_key.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_func_get_public_key.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_func_signer_to_guid.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_func_signer_to_guid.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_func_validate_felt.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_func_validate_felt.restype = ctypes.c_int8
_UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_from_storage.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_from_storage.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_new.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_new_headless.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_new_headless.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_address.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_address.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_app_id.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_app_id.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_chain_id.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_chain_id.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_clear_last_error.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_clear_last_error.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_delegate_account.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_delegate_account.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_disconnect.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_disconnect.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_error_message.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_error_message.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_execute.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_execute.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_signup.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_signup.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_switch_chain.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_switch_chain.restype = None
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_transfer.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_transfer.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_username.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_controller_username.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_constructor_owner_new.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_constructor_owner_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_constructor_sessionaccount_create_from_subscribe.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_constructor_sessionaccount_create_from_subscribe.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_constructor_sessionaccount_new.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_constructor_sessionaccount_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_controller_uniffi_fn_method_sessionaccount_execute.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_sessionaccount_execute.restype = _UniffiRustBuffer
_UniffiLib.uniffi_controller_uniffi_fn_method_sessionaccount_execute_from_outside.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_controller_uniffi_fn_method_sessionaccount_execute_from_outside.restype = _UniffiRustBuffer
_UniffiLib.ffi_controller_uniffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_controller_uniffi_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_controller_uniffi_checksum_func_controller_has_storage.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_func_controller_has_storage.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_func_get_controller_class_hash.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_func_get_controller_class_hash.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_func_get_public_key.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_func_get_public_key.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_func_signer_to_guid.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_func_signer_to_guid.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_func_validate_felt.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_func_validate_felt.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_controller_from_storage.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_controller_from_storage.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_controller_new.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_controller_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_controller_new_headless.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_controller_new_headless.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_address.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_address.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_app_id.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_app_id.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_chain_id.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_chain_id.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_clear_last_error.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_clear_last_error.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_delegate_account.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_delegate_account.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_disconnect.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_disconnect.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_error_message.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_error_message.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_execute.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_execute.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_signup.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_signup.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_switch_chain.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_switch_chain.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_transfer.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_transfer.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_username.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_controller_username.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_owner_new.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_owner_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_sessionaccount_create_from_subscribe.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_sessionaccount_create_from_subscribe.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_sessionaccount_new.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_constructor_sessionaccount_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_sessionaccount_execute.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_sessionaccount_execute.restype = ctypes.c_uint16
_UniffiLib.uniffi_controller_uniffi_checksum_method_sessionaccount_execute_from_outside.argtypes = (
)
_UniffiLib.uniffi_controller_uniffi_checksum_method_sessionaccount_execute_from_outside.restype = ctypes.c_uint16

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()


class _UniffiFfiConverterTypeFieldElement:
    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value, buf)

    @staticmethod
    def read(buf):
        return _UniffiFfiConverterString.read(buf)

    @staticmethod
    def lift(value):
        return _UniffiFfiConverterString.lift(value)

    @staticmethod
    def check_lower(value):
        return _UniffiFfiConverterString.check_lower(value)

    @staticmethod
    def lower(value):
        return _UniffiFfiConverterString.lower(value)


FieldElement = str

class _UniffiFfiConverterSequenceTypeFieldElement(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeFieldElement.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeFieldElement.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeFieldElement.read(buf) for i in range(count)
        ]

@dataclass
class Call:
    def __init__(self, *, contract_address:FieldElement, entrypoint:str, calldata:typing.List[FieldElement]):
        self.contract_address = contract_address
        self.entrypoint = entrypoint
        self.calldata = calldata
        
        

    
    def __str__(self):
        return "Call(contract_address={}, entrypoint={}, calldata={})".format(self.contract_address, self.entrypoint, self.calldata)
    def __eq__(self, other):
        if self.contract_address != other.contract_address:
            return False
        if self.entrypoint != other.entrypoint:
            return False
        if self.calldata != other.calldata:
            return False
        return True

class _UniffiFfiConverterTypeCall(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Call(
            contract_address=_UniffiFfiConverterTypeFieldElement.read(buf),
            entrypoint=_UniffiFfiConverterString.read(buf),
            calldata=_UniffiFfiConverterSequenceTypeFieldElement.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterTypeFieldElement.check_lower(value.contract_address)
        _UniffiFfiConverterString.check_lower(value.entrypoint)
        _UniffiFfiConverterSequenceTypeFieldElement.check_lower(value.calldata)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterTypeFieldElement.write(value.contract_address, buf)
        _UniffiFfiConverterString.write(value.entrypoint, buf)
        _UniffiFfiConverterSequenceTypeFieldElement.write(value.calldata, buf)

@dataclass
class SessionPolicy:
    def __init__(self, *, contract_address:FieldElement, entrypoint:str):
        self.contract_address = contract_address
        self.entrypoint = entrypoint
        
        

    
    def __str__(self):
        return "SessionPolicy(contract_address={}, entrypoint={})".format(self.contract_address, self.entrypoint)
    def __eq__(self, other):
        if self.contract_address != other.contract_address:
            return False
        if self.entrypoint != other.entrypoint:
            return False
        return True

class _UniffiFfiConverterTypeSessionPolicy(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SessionPolicy(
            contract_address=_UniffiFfiConverterTypeFieldElement.read(buf),
            entrypoint=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterTypeFieldElement.check_lower(value.contract_address)
        _UniffiFfiConverterString.check_lower(value.entrypoint)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterTypeFieldElement.write(value.contract_address, buf)
        _UniffiFfiConverterString.write(value.entrypoint, buf)

class _UniffiFfiConverterSequenceTypeSessionPolicy(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeSessionPolicy.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeSessionPolicy.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeSessionPolicy.read(buf) for i in range(count)
        ]

@dataclass
class SessionPolicies:
    def __init__(self, *, policies:typing.List[SessionPolicy], max_fee:FieldElement):
        self.policies = policies
        self.max_fee = max_fee
        
        

    
    def __str__(self):
        return "SessionPolicies(policies={}, max_fee={})".format(self.policies, self.max_fee)
    def __eq__(self, other):
        if self.policies != other.policies:
            return False
        if self.max_fee != other.max_fee:
            return False
        return True

class _UniffiFfiConverterTypeSessionPolicies(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SessionPolicies(
            policies=_UniffiFfiConverterSequenceTypeSessionPolicy.read(buf),
            max_fee=_UniffiFfiConverterTypeFieldElement.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceTypeSessionPolicy.check_lower(value.policies)
        _UniffiFfiConverterTypeFieldElement.check_lower(value.max_fee)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceTypeSessionPolicy.write(value.policies, buf)
        _UniffiFfiConverterTypeFieldElement.write(value.max_fee, buf)



# ControllerError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class ControllerError(Exception):
    pass

_UniffiTempControllerError = ControllerError

class ControllerError:  # type: ignore
    
    class InitializationError(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.InitializationError({})".format(str(self))
    _UniffiTempControllerError.InitializationError = InitializationError # type: ignore
    class SignupError(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.SignupError({})".format(str(self))
    _UniffiTempControllerError.SignupError = SignupError # type: ignore
    class ExecutionError(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.ExecutionError({})".format(str(self))
    _UniffiTempControllerError.ExecutionError = ExecutionError # type: ignore
    class NetworkError(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.NetworkError({})".format(str(self))
    _UniffiTempControllerError.NetworkError = NetworkError # type: ignore
    class StorageError(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.StorageError({})".format(str(self))
    _UniffiTempControllerError.StorageError = StorageError # type: ignore
    class InvalidInput(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.InvalidInput({})".format(str(self))
    _UniffiTempControllerError.InvalidInput = InvalidInput # type: ignore
    class DisconnectError(_UniffiTempControllerError):
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "ControllerError.DisconnectError({})".format(str(self))
    _UniffiTempControllerError.DisconnectError = DisconnectError # type: ignore

ControllerError = _UniffiTempControllerError # type: ignore
del _UniffiTempControllerError


class _UniffiFfiConverterTypeControllerError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ControllerError.InitializationError(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return ControllerError.SignupError(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return ControllerError.ExecutionError(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return ControllerError.NetworkError(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return ControllerError.StorageError(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 6:
            return ControllerError.InvalidInput(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 7:
            return ControllerError.DisconnectError(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, ControllerError.InitializationError):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, ControllerError.SignupError):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, ControllerError.ExecutionError):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, ControllerError.NetworkError):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, ControllerError.StorageError):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, ControllerError.InvalidInput):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, ControllerError.DisconnectError):
            _UniffiFfiConverterString.check_lower(value._values[0])
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, ControllerError.InitializationError):
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if isinstance(value, ControllerError.SignupError):
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if isinstance(value, ControllerError.ExecutionError):
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if isinstance(value, ControllerError.NetworkError):
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if isinstance(value, ControllerError.StorageError):
            buf.write_i32(5)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if isinstance(value, ControllerError.InvalidInput):
            buf.write_i32(6)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if isinstance(value, ControllerError.DisconnectError):
            buf.write_i32(7)
            _UniffiFfiConverterString.write(value._values[0], buf)






class SignerType(enum.Enum):
    
    WEBAUTHN = 0
    
    STARKNET = 1
    


class _UniffiFfiConverterTypeSignerType(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return SignerType.WEBAUTHN
        if variant == 2:
            return SignerType.STARKNET
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == SignerType.WEBAUTHN:
            return
        if value == SignerType.STARKNET:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == SignerType.WEBAUTHN:
            buf.write_i32(1)
        if value == SignerType.STARKNET:
            buf.write_i32(2)








class Version(enum.Enum):
    
    V1_0_4 = 0
    
    V1_0_5 = 1
    
    V1_0_6 = 2
    
    V1_0_7 = 3
    
    V1_0_8 = 4
    
    V1_0_9 = 5
    
    LATEST = 6
    


class _UniffiFfiConverterTypeVersion(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Version.V1_0_4
        if variant == 2:
            return Version.V1_0_5
        if variant == 3:
            return Version.V1_0_6
        if variant == 4:
            return Version.V1_0_7
        if variant == 5:
            return Version.V1_0_8
        if variant == 6:
            return Version.V1_0_9
        if variant == 7:
            return Version.LATEST
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Version.V1_0_4:
            return
        if value == Version.V1_0_5:
            return
        if value == Version.V1_0_6:
            return
        if value == Version.V1_0_7:
            return
        if value == Version.V1_0_8:
            return
        if value == Version.V1_0_9:
            return
        if value == Version.LATEST:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Version.V1_0_4:
            buf.write_i32(1)
        if value == Version.V1_0_5:
            buf.write_i32(2)
        if value == Version.V1_0_6:
            buf.write_i32(3)
        if value == Version.V1_0_7:
            buf.write_i32(4)
        if value == Version.V1_0_8:
            buf.write_i32(5)
        if value == Version.V1_0_9:
            buf.write_i32(6)
        if value == Version.LATEST:
            buf.write_i32(7)



class _UniffiFfiConverterSequenceTypeCall(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeCall.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeCall.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeCall.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterOptionalUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt64.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")


class ControllerProtocol(typing.Protocol):
    
    def address(self, ) -> FieldElement:
        raise NotImplementedError
    def app_id(self, ) -> str:
        raise NotImplementedError
    def chain_id(self, ) -> FieldElement:
        raise NotImplementedError
    def clear_last_error(self, ) -> None:
        raise NotImplementedError
    def delegate_account(self, ) -> FieldElement:
        raise NotImplementedError
    def disconnect(self, ) -> None:
        raise NotImplementedError
    def error_message(self, ) -> str:
        raise NotImplementedError
    def execute(self, calls: typing.List[Call]) -> FieldElement:
        raise NotImplementedError
    def signup(self, signer_type: SignerType,session_expiration: typing.Optional[int],cartridge_api_url: typing.Optional[str]) -> None:
        raise NotImplementedError
    def switch_chain(self, rpc_url: str) -> None:
        raise NotImplementedError
    def transfer(self, recipient: FieldElement,amount: FieldElement) -> FieldElement:
        raise NotImplementedError
    def username(self, ) -> str:
        raise NotImplementedError

class Controller(ControllerProtocol):
    
    _handle: ctypes.c_uint64
    @classmethod
    def from_storage(cls, app_id: str) -> Controller:
        
        _UniffiFfiConverterString.check_lower(app_id)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(app_id),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeController.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_from_storage,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)
    def __init__(self, app_id: str,username: str,class_hash: FieldElement,rpc_url: str,owner: Owner,address: FieldElement,chain_id: FieldElement):
        
        _UniffiFfiConverterString.check_lower(app_id)
        
        _UniffiFfiConverterString.check_lower(username)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(class_hash)
        
        _UniffiFfiConverterString.check_lower(rpc_url)
        
        _UniffiFfiConverterTypeOwner.check_lower(owner)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(address)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(chain_id)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(app_id),
            _UniffiFfiConverterString.lower(username),
            _UniffiFfiConverterTypeFieldElement.lower(class_hash),
            _UniffiFfiConverterString.lower(rpc_url),
            _UniffiFfiConverterTypeOwner.lower(owner),
            _UniffiFfiConverterTypeFieldElement.lower(address),
            _UniffiFfiConverterTypeFieldElement.lower(chain_id),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeController.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result
    @classmethod
    def new_headless(cls, app_id: str,username: str,class_hash: FieldElement,rpc_url: str,owner: Owner,chain_id: FieldElement) -> Controller:
        
        _UniffiFfiConverterString.check_lower(app_id)
        
        _UniffiFfiConverterString.check_lower(username)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(class_hash)
        
        _UniffiFfiConverterString.check_lower(rpc_url)
        
        _UniffiFfiConverterTypeOwner.check_lower(owner)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(chain_id)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(app_id),
            _UniffiFfiConverterString.lower(username),
            _UniffiFfiConverterTypeFieldElement.lower(class_hash),
            _UniffiFfiConverterString.lower(rpc_url),
            _UniffiFfiConverterTypeOwner.lower(owner),
            _UniffiFfiConverterTypeFieldElement.lower(chain_id),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeController.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_constructor_controller_new_headless,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_controller_uniffi_fn_free_controller, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_controller_uniffi_fn_clone_controller, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def address(self, ) -> FieldElement:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_address,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def app_id(self, ) -> str:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_app_id,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def chain_id(self, ) -> FieldElement:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_chain_id,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def clear_last_error(self, ) -> None:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_clear_last_error,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def delegate_account(self, ) -> FieldElement:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_delegate_account,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def disconnect(self, ) -> None:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_disconnect,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def error_message(self, ) -> str:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_error_message,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def execute(self, calls: typing.List[Call]) -> FieldElement:
        
        _UniffiFfiConverterSequenceTypeCall.check_lower(calls)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterSequenceTypeCall.lower(calls),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_execute,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def signup(self, signer_type: SignerType,session_expiration: typing.Optional[int],cartridge_api_url: typing.Optional[str]) -> None:
        
        _UniffiFfiConverterTypeSignerType.check_lower(signer_type)
        
        _UniffiFfiConverterOptionalUInt64.check_lower(session_expiration)
        
        _UniffiFfiConverterOptionalString.check_lower(cartridge_api_url)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterTypeSignerType.lower(signer_type),
            _UniffiFfiConverterOptionalUInt64.lower(session_expiration),
            _UniffiFfiConverterOptionalString.lower(cartridge_api_url),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_signup,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def switch_chain(self, rpc_url: str) -> None:
        
        _UniffiFfiConverterString.check_lower(rpc_url)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(rpc_url),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_switch_chain,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def transfer(self, recipient: FieldElement,amount: FieldElement) -> FieldElement:
        
        _UniffiFfiConverterTypeFieldElement.check_lower(recipient)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(amount)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterTypeFieldElement.lower(recipient),
            _UniffiFfiConverterTypeFieldElement.lower(amount),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_transfer,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def username(self, ) -> str:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_controller_username,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeController:
    @staticmethod
    def lift(value: int) -> Controller:
        return Controller._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: Controller):
        if not isinstance(value, Controller):
            raise TypeError("Expected Controller instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: Controller) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> Controller:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: Controller, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class OwnerProtocol(typing.Protocol):
    
    pass

class Owner(OwnerProtocol):
    
    _handle: ctypes.c_uint64
    def __init__(self, private_key: str):
        
        _UniffiFfiConverterString.check_lower(private_key)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(private_key),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeOwner.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_constructor_owner_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_controller_uniffi_fn_free_owner, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_controller_uniffi_fn_clone_owner, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst





class _UniffiFfiConverterTypeOwner:
    @staticmethod
    def lift(value: int) -> Owner:
        return Owner._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: Owner):
        if not isinstance(value, Owner):
            raise TypeError("Expected Owner instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: Owner) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> Owner:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: Owner, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class SessionAccountProtocol(typing.Protocol):
    
    def execute(self, calls: typing.List[Call]) -> FieldElement:
        raise NotImplementedError
    def execute_from_outside(self, calls: typing.List[Call]) -> FieldElement:
        raise NotImplementedError

class SessionAccount(SessionAccountProtocol):
    
    _handle: ctypes.c_uint64
    @classmethod
    def create_from_subscribe(cls, private_key: str,policies: SessionPolicies,rpc_url: str,cartridge_api_url: str) -> SessionAccount:
        
        _UniffiFfiConverterString.check_lower(private_key)
        
        _UniffiFfiConverterTypeSessionPolicies.check_lower(policies)
        
        _UniffiFfiConverterString.check_lower(rpc_url)
        
        _UniffiFfiConverterString.check_lower(cartridge_api_url)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(private_key),
            _UniffiFfiConverterTypeSessionPolicies.lower(policies),
            _UniffiFfiConverterString.lower(rpc_url),
            _UniffiFfiConverterString.lower(cartridge_api_url),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeSessionAccount.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_constructor_sessionaccount_create_from_subscribe,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)
    def __init__(self, rpc_url: str,private_key: str,address: FieldElement,owner_guid: FieldElement,chain_id: FieldElement,policies: SessionPolicies,session_expiration: int):
        
        _UniffiFfiConverterString.check_lower(rpc_url)
        
        _UniffiFfiConverterString.check_lower(private_key)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(address)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(owner_guid)
        
        _UniffiFfiConverterTypeFieldElement.check_lower(chain_id)
        
        _UniffiFfiConverterTypeSessionPolicies.check_lower(policies)
        
        _UniffiFfiConverterUInt64.check_lower(session_expiration)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(rpc_url),
            _UniffiFfiConverterString.lower(private_key),
            _UniffiFfiConverterTypeFieldElement.lower(address),
            _UniffiFfiConverterTypeFieldElement.lower(owner_guid),
            _UniffiFfiConverterTypeFieldElement.lower(chain_id),
            _UniffiFfiConverterTypeSessionPolicies.lower(policies),
            _UniffiFfiConverterUInt64.lower(session_expiration),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeSessionAccount.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_constructor_sessionaccount_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_controller_uniffi_fn_free_sessionaccount, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_controller_uniffi_fn_clone_sessionaccount, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def execute(self, calls: typing.List[Call]) -> FieldElement:
        
        _UniffiFfiConverterSequenceTypeCall.check_lower(calls)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterSequenceTypeCall.lower(calls),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_sessionaccount_execute,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def execute_from_outside(self, calls: typing.List[Call]) -> FieldElement:
        
        _UniffiFfiConverterSequenceTypeCall.check_lower(calls)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterSequenceTypeCall.lower(calls),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_controller_uniffi_fn_method_sessionaccount_execute_from_outside,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeSessionAccount:
    @staticmethod
    def lift(value: int) -> SessionAccount:
        return SessionAccount._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: SessionAccount):
        if not isinstance(value, SessionAccount):
            raise TypeError("Expected SessionAccount instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: SessionAccount) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> SessionAccount:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: SessionAccount, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiFfiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)
def controller_has_storage(app_id: str) -> bool:
    
    _UniffiFfiConverterString.check_lower(app_id)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(app_id),
    )
    _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_controller_uniffi_fn_func_controller_has_storage,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def get_controller_class_hash(version: Version) -> FieldElement:
    """
    Get the class hash for a specific controller version
"""
    
    _UniffiFfiConverterTypeVersion.check_lower(version)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeVersion.lower(version),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_controller_uniffi_fn_func_get_controller_class_hash,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def get_public_key(private_key: FieldElement) -> FieldElement:
    
    _UniffiFfiConverterTypeFieldElement.check_lower(private_key)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeFieldElement.lower(private_key),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_controller_uniffi_fn_func_get_public_key,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def signer_to_guid(private_key: FieldElement) -> FieldElement:
    
    _UniffiFfiConverterTypeFieldElement.check_lower(private_key)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeFieldElement.lower(private_key),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeFieldElement.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_controller_uniffi_fn_func_signer_to_guid,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def validate_felt(felt: str) -> bool:
    """
    Utility functions
"""
    
    _UniffiFfiConverterString.check_lower(felt)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(felt),
    )
    _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeControllerError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_controller_uniffi_fn_func_validate_felt,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "ControllerError",
    "SignerType",
    "Version",
    "Call",
    "SessionPolicy",
    "SessionPolicies",
    "controller_has_storage",
    "get_controller_class_hash",
    "get_public_key",
    "signer_to_guid",
    "validate_felt",
    "Controller",
    "ControllerProtocol",
    "Owner",
    "OwnerProtocol",
    "SessionAccount",
    "SessionAccountProtocol",
]