#!/bin/bash

set -e

echo "Building Controller C Bindings..."
echo "================================"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Build the Rust library
echo -e "\n${GREEN}Building Rust library...${NC}"
cargo build --release

# Generate headers
echo -e "\n${GREEN}Headers generated by build.rs${NC}"
ls -la controller.h controller.hpp 2>/dev/null || echo "Headers will be generated on first build"

# Build examples if requested
if [[ "$1" == "--examples" ]]; then
    echo -e "\n${GREEN}Building examples...${NC}"
    cd example
    make clean
    make all
    cd ..
    echo -e "${GREEN}Examples built successfully!${NC}"
fi

# Run tests if requested
if [[ "$1" == "--test" || "$2" == "--test" ]]; then
    echo -e "\n${GREEN}Running tests...${NC}"
    cargo test
fi

echo -e "\n${GREEN}Build completed successfully!${NC}"
echo "Library location: target/release/libcontroller_c.*"
echo "Headers: controller.h, controller.hpp"

if [[ "$1" != "--examples" ]]; then
    echo -e "\nTo build examples, run: ${GREEN}./scripts/build.sh --examples${NC}"
fi