// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
#pragma once
#include <jsi/jsi.h>
#include <iostream>
#include <map>
#include <memory>
#include <ReactCommon/CallInvoker.h>
#include "UniffiCallInvoker.h"

namespace react = facebook::react;
namespace jsi = facebook::jsi;

class NativeController : public jsi::HostObject {
  private:
    // For calling back into JS from Rust.
    std::shared_ptr<uniffi_runtime::UniffiCallInvoker> callInvoker;

  protected:
    std::map<std::string,jsi::Value> props;
    jsi::Value cpp_uniffi_internal_fn_func_ffi__string_to_byte_length(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_func_ffi__string_to_arraybuffer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_func_ffi__arraybuffer_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_clone_controller(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_free_controller(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_constructor_controller_from_storage(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_constructor_controller_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_constructor_controller_new_headless(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_address(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_app_id(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_chain_id(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_clear_last_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_delegate_account(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_disconnect(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_error_message(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_execute(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_signup(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_switch_chain(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_transfer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_controller_username(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_clone_owner(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_free_owner(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_constructor_owner_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_clone_sessionaccount(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_free_sessionaccount(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_constructor_sessionaccount_create_from_subscribe(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_constructor_sessionaccount_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_sessionaccount_execute(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_method_sessionaccount_execute_from_outside(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_func_controller_has_storage(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_func_get_controller_class_hash(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_func_get_public_key(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_func_signer_to_guid(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_fn_func_validate_felt(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_func_controller_has_storage(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_func_get_controller_class_hash(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_func_get_public_key(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_func_signer_to_guid(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_func_validate_felt(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_address(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_app_id(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_chain_id(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_clear_last_error(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_delegate_account(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_disconnect(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_error_message(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_execute(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_signup(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_switch_chain(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_transfer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_controller_username(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_sessionaccount_execute(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_method_sessionaccount_execute_from_outside(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_constructor_controller_from_storage(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_constructor_controller_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_constructor_controller_new_headless(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_constructor_owner_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_constructor_sessionaccount_create_from_subscribe(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_controller_uniffi_checksum_constructor_sessionaccount_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_controller_uniffi_uniffi_contract_version(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_Controller__bless_pointer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_Owner__bless_pointer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_SessionAccount__bless_pointer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);

  public:
    NativeController(jsi::Runtime &rt, std::shared_ptr<uniffi_runtime::UniffiCallInvoker> callInvoker);
    virtual ~NativeController();

    /**
     * The entry point into the crate.
     *
     * React Native must call `NativeController.registerModule(rt, callInvoker)` before using
     * the Javascript interface.
     */
    static void registerModule(jsi::Runtime &rt, std::shared_ptr<react::CallInvoker> callInvoker);

    /**
     * Some cleanup into the crate goes here.
     *
     * Current implementation is empty, however, this is not guaranteed to always be the case.
     *
     * Clients should call `NativeController.unregisterModule(rt)` after final use where possible.
     */
    static void unregisterModule(jsi::Runtime &rt);

    virtual jsi::Value get(jsi::Runtime& rt, const jsi::PropNameID& name);
    virtual void set(jsi::Runtime& rt,const jsi::PropNameID& name,const jsi::Value& value);
    virtual std::vector<jsi::PropNameID> getPropertyNames(jsi::Runtime& rt);
};